name: Autograde Selfie Assignment

on:
  push:
    paths:
    - '**.c'
    - '**.yml'

jobs:
  auto-grade-selfie-assignment:
    name: Run autograder
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    # extract assignment from "commit message [assignment]"
    - name: Parse commit message
      run: echo "ASSIGNMENT=$(echo $COMMIT_MESSAGE | awk -F '[][]' '{print $2}')" >> $GITHUB_ENV
    - name: Autograde assignment
      run: if [ "$ASSIGNMENT" != 'skip ci' ]; then ./grader/self.py $ASSIGNMENT; fi